#!/usr/bin/env bash
set -euo pipefail

# Fetch only the Mathlib modules imported directly by the current formal layer,
# plus their transitive dependencies. This is intentionally narrower than
# `lake exe cache get`, which downloads the cache for all of Mathlib.
#
# Keep this list synchronized with direct Mathlib imports under formal/.
lake exe cache get \
  Mathlib.Algebra.BigOperators.Fin \
  Mathlib.Data.Real.Basic \
  Mathlib.Data.Finset.Max \
  Mathlib.Data.Finset.Card \
  Mathlib.InformationTheory.KullbackLeibler.DataProcessing \
  Mathlib.MeasureTheory.Function.FactorsThrough \
  Mathlib.Probability.Independence.Conditional \
  Mathlib.Probability.Kernel.Composition.Lemmas \
  Mathlib.Algebra.Order.BigOperators.Group.Finset \
  Mathlib.Algebra.BigOperators.Field \
  Mathlib.Logic.Function.Iterate \
  Mathlib.Tactic.Push \
  Mathlib.Analysis.Calculus.MeanValue \
  Mathlib.Logic.Equiv.Basic \
  Mathlib.Tactic.Ring \
  Mathlib.Tactic.Linarith \
  Mathlib.Data.Setoid.Basic \
  Mathlib.Logic.Function.Basic \
  Mathlib.SetTheory.Cardinal.Finite \
  Mathlib.GroupTheory.GroupAction.Defs \
  Mathlib.Analysis.SpecialFunctions.Log.Basic \
  Mathlib.Data.Fintype.Prod \
  Mathlib.Tactic.NormNum \
  Mathlib.Analysis.InnerProductSpace.Calculus \
  Mathlib.Analysis.SpecialFunctions.Sqrt \
  Mathlib.Analysis.Calculus.Deriv.Inv \
  Mathlib.Analysis.Calculus.FDeriv.Mul \
  Mathlib.Algebra.Group.Hom.Defs \
  Mathlib.Analysis.Calculus.Deriv.Add \
  Mathlib.Analysis.Calculus.Deriv.Comp \
  Mathlib.Analysis.Calculus.Deriv.Mul \
  Mathlib.Analysis.Calculus.FDeriv.Prod \
  Mathlib.Analysis.InnerProductSpace.LinearMap \
  Mathlib.Analysis.InnerProductSpace.Projection.Basic \
  Mathlib.Analysis.InnerProductSpace.Projection.FiniteDimensional \
  Mathlib.Analysis.Normed.Operator.Basic \
  Mathlib.Analysis.SpecificLimits.Normed \
  Mathlib.Data.Quot \
  Mathlib.LinearAlgebra.Dimension.StrongRankCondition \
  Mathlib.LinearAlgebra.FiniteDimensional.Basic \
  Mathlib.LinearAlgebra.FiniteDimensional.Lemmas \
  Mathlib.LinearAlgebra.Matrix.Charpoly.Basic \
  Mathlib.LinearAlgebra.Matrix.Trace \
  Mathlib.LinearAlgebra.Prod \
  Mathlib.MeasureTheory.Measure.Lebesgue.EqHaar \
  Mathlib.Tactic.FieldSimp \
  Mathlib.LinearAlgebra.Dimension.Constructions \
  Mathlib.LinearAlgebra.Dimension.Free \
  Mathlib.LinearAlgebra.Matrix.Charpoly.Coeff \
  Mathlib.RepresentationTheory.Basic \
  Mathlib.Tactic.Abel \
  Mathlib.Algebra.Order.AbsoluteValue.Basic \
  Mathlib.Data.Rat.Floor \
  Mathlib.Topology.MetricSpace.Basic \
  Mathlib.Topology.MetricSpace.Isometry \
  Mathlib.Analysis.Calculus.FDeriv.Comp \
  Mathlib.Analysis.Calculus.FDeriv.Basic \
  Mathlib.Analysis.Calculus.Deriv.Pow \
  Mathlib.Analysis.SpecificLimits.Basic \
  Mathlib.Analysis.Calculus.FDeriv.Symmetric \
  Mathlib.Analysis.Calculus.Gradient.Basic \
  Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv \
  Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic \
  Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus \
  Mathlib.Data.Nat.Choose.Sum \
  Mathlib.Data.Nat.Choose.Bounds \
  Mathlib.Algebra.Algebra.Basic \
  Mathlib.Analysis.Normed.Algebra.Basic \
  Mathlib.Topology.Order.LiminfLimsup \
  Mathlib.Analysis.Normed.Operator.Prod \
  Mathlib.Analysis.Normed.Lp.PiLp \
  Mathlib.Combinatorics.SimpleGraph.Acyclic \
  Mathlib.Analysis.InnerProductSpace.Basic \
  Mathlib.Analysis.InnerProductSpace.PiL2 \
  Mathlib.Analysis.InnerProductSpace.SingularValues \
  Mathlib.Analysis.InnerProductSpace.ProdL2 \
  Mathlib.Analysis.InnerProductSpace.TensorProduct \
  Mathlib.LinearAlgebra.FreeModule.Finite.Matrix \
  Mathlib.LinearAlgebra.Matrix.Rank \
  Mathlib.LinearAlgebra.Projectivization.Basic \
  Mathlib.Analysis.InnerProductSpace.GramMatrix \
  Mathlib.Analysis.Matrix.Order \
  Mathlib.Analysis.Matrix.Normed \
  Mathlib.LinearAlgebra.Matrix.Kronecker \
  Mathlib.Tactic.FinCases \
  Mathlib.AlgebraicTopology.SimplicialComplex.Basic \
  Mathlib.Data.Set.Function \
  Mathlib.LinearAlgebra.Matrix.ToLin \
  Mathlib.Order.Interval.Finset.Basic \
  Mathlib.LinearAlgebra.Matrix.Notation \
  Mathlib.LinearAlgebra.Dimension.RankNullity \
  Mathlib.Data.Nat.SuccPred \
  Mathlib.Topology.Algebra.InfiniteSum.Real \
  Mathlib.GroupTheory.Congruence.Hom \
  Mathlib.Algebra.BigOperators.Group.List.Lemmas \
  Mathlib.LinearAlgebra.Eigenspace.Charpoly \
  Mathlib.Analysis.Calculus.ContDiff.Operations \
  Mathlib.Geometry.Manifold.IsManifold.Basic \
  Mathlib.Analysis.Normed.Module.FiniteDimension \
  Mathlib.LinearAlgebra.BilinearForm.Orthogonal \
  Mathlib.Geometry.Manifold.ContMDiff.Atlas \
  Mathlib.Geometry.Manifold.Diffeomorph \
  Mathlib.Analysis.InnerProductSpace.Adjoint \
  Mathlib.Geometry.Manifold.Instances.Sphere \
  Mathlib.Analysis.Calculus.Deriv.Abs \
  Mathlib.LinearAlgebra.Matrix.BilinearForm \
  Mathlib.LinearAlgebra.Center \
  Mathlib.LinearAlgebra.Eigenspace.Pi \
  Mathlib.LinearAlgebra.Eigenspace.Semisimple \
  Mathlib.Algebra.DirectSum.Module \
  Mathlib.LinearAlgebra.Complex.FiniteDimensional \
  Mathlib.Analysis.SpecialFunctions.Complex.Arg \
  Mathlib.Geometry.Manifold.Instances.Quotient \
  Mathlib.Geometry.Manifold.Algebra.SMul \
  Mathlib.Geometry.Manifold.MFDeriv.Atlas \
  Mathlib.Geometry.Manifold.MFDeriv.NormedSpace \
  Mathlib.Algebra.Module.TransferInstance \
  Mathlib.Probability.Kernel.Composition.CompMap \
  Mathlib.MeasureTheory.Integral.Bochner.Basic \
  Mathlib.MeasureTheory.Measure.CharacteristicFunction.Basic \
  Mathlib.Data.Nat.Pairing \
  Mathlib.Analysis.SpecialFunctions.Integrals.Basic \
  Mathlib.Analysis.SpecialFunctions.Trigonometric.DerivHyp \
  Mathlib.Topology.MetricSpace.CoveringNumbers \
  Mathlib.Analysis.Calculus.InverseFunctionTheorem.FDeriv \
  Mathlib.Analysis.Normed.Module.ContinuousInverse \
  Mathlib.Analysis.Calculus.ContDiff.RCLike \
  Mathlib.Analysis.Calculus.InverseFunctionTheorem.ContDiff \
  Mathlib.LinearAlgebra.Finsupp.Defs \
  Mathlib.LinearAlgebra.Finsupp.LinearCombination \
  Mathlib.LinearAlgebra.Quotient.Basic \
  Mathlib.GroupTheory.FreeGroup.Reduce \
  Mathlib.GroupTheory.Commutator.Basic \
  Mathlib.GroupTheory.Perm.Basic \
  Mathlib.Topology.MetricSpace.Contracting \
  Mathlib.Geometry.Manifold.SmoothEmbedding
